import type { Metadata } from "next";
import localFont from "next/font/local";
import { AuthProviders } from "./auth-providers";
import "./globals.css";


const impactFont = localFont({
  src: './fonts/impact.ttf',  // Adjust this path if necessary
  variable: '--font-impact',
})

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const minecraftFont = localFont({
  src: './fonts/minecraft.ttf',
  variable: '--font-minecraft',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProviders>
        <body 
          className={`${minecraftFont.variable} ${impactFont.variable} antialiased font-minecraft`}
          style={{ fontFamily: 'var(--font-minecraft), var(--font-impact), sans-serif' }}
        >
          {children}
        </body>
      </AuthProviders>
    </html>
  );
}
